name: Protect Production

on:
  pull_request:
    branches:
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        if [ ${GITHUB_ACTOR} != "genebean" ]; then
          echo "::error ::Only CD4PE may submit changes to production. Please make your PR target master instead."
        fi
